In [1]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [21]:
#import datasets
df = pd.read_csv('Data.csv')
X=df.iloc[:,:-1].values #except last column
Y=df.iloc[:,-1].values #only last column

In [33]:
#Data Cleaning/Taking care of missing data and feature scaling
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])#need to fit using the means in first 3 columns
X[:,1:3]=imputer.transform(X[:,1:3])#replace the nan with the calculated mean and hence transform
print(X)
print('-------------------------------------------------')
print('--------Independent Variable transformer---------')
print('-------------------------------------------------')
#Further cleaning/formatting the data - encoding the independent and dependent variables
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)
print('-----------------------------------------------------')
print('--------Dependent Variable/Label transformer---------')
print('-----------------------------------------------------')
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)
print(Y)

[[1.0 0.0 1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]
-------------------------------------------------
--------Independent Variable transformer---------
-------------------------------------------------
[[0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0

In [36]:
#Split Data into train and test set
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=1)

print('X_train:')
print(X_train)
print('X_test:')
print(X_test)
print('Y_train:')
print(Y_train)
print('Y_test:')
print(Y_test)
#see the result, since there are 10 samples, 8 are there in train indicating 80% of training data

X_train:
[[1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 35.0 58000.0]]
X_test:
[[1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]
Y_train:
[0 1 0 0 1 1 0 1]
Y_test:
[0 1]


In [38]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.fit_transform(X_test[:,3:])
print('X_train')
print(X_train)
print('X_test')
print(X_test)

X_train
[[1.0 0.0 1.0 -0.7745966692414834 0.7745966692414834 -0.7745966692414834
  -0.5773502691896258 1.2909944487358056 -0.19159184384578545
  -1.0781259408412425]
 [1.0 0.0 1.0 -0.7745966692414834 0.7745966692414834 -0.7745966692414834
  1.7320508075688774 -0.7745966692414834 -0.014117293757057777
  -0.07013167641635372]
 [0.0 1.0 0.0 1.2909944487358056 -1.2909944487358056 1.2909944487358056
  -0.5773502691896258 -0.7745966692414834 0.566708506533324
  0.633562432710455]
 [1.0 0.0 1.0 -0.7745966692414834 0.7745966692414834 -0.7745966692414834
  -0.5773502691896258 1.2909944487358056 -0.30453019390224867
  -0.30786617274297867]
 [1.0 0.0 1.0 -0.7745966692414834 0.7745966692414834 -0.7745966692414834
  -0.5773502691896258 1.2909944487358056 -1.9018011447007988
  -1.420463615551582]
 [0.0 1.0 0.0 1.2909944487358056 -1.2909944487358056 1.2909944487358056
  -0.5773502691896258 -0.7745966692414834 1.1475343068237058
  1.232653363453549]
 [1.0 0.0 1.0 -0.7745966692414834 0.7745966692414834